### ISSUE TITLE
How to install checkpointctl tool

### ISSUE THREAD

**Issue by anshitha1706** [checkpoint-restore/checkpointctl#1]
Hello @adrianreber I am new to K8 and right now working on Application migration between two different clusters for my Master Thesis. This tool looks very promising and I would like to try it to manipulate with checkpoinzs. However, I am unable to install it as I do not see any instructions anywhere.

**Comment by adrianreber** [comment]
Just run`make`. Doesn't that work for you?

**Comment by anshitha1706** [comment]
Yes, I tried it now, but now it saya that the module required go version 1.15. Mine is 1.12. I will try fixing it. Thank you! :)

**Comment by adrianreber** [comment]
`go.mod` says 1.15 because that is the version I am using locally. I am not aware of any special Golang features I am using. So you could try to change that and see if it also works with 1.12.

**Comment by anshitha1706** [comment]
I changed the version to 1.15 now. But now the error is as follows:make
go build -buildmode=pie -o checkpointctl -ldflags "-X main.name=checkpointctl"
go build github.com/checkpoint-restore/checkpointctl: copying /tmp/go-build423642275/b001/exe/a.out: open checkpointctl: permission denied
make: *** [Makefile:12: checkpointctl] Error 1

What must be the reason? How do I solve this?

**Comment by anshitha1706** [comment]
I also tried using sudo as it says permission denied, it still does'nt work.

**Comment by adrianreber** [comment]
Works for me locally on Fedora 33 and in CI on Ubuntu 20.04. Closing this as it seems to be a problem with your setup.

**Comment by anshitha1706** [comment]
I git cloned the repository again and then ran the 'make' command again and it worked with no errors. But how do I test if the tool is working? I ran checkpoint command on the CLI, but it said comman not found.

**Comment by adrianreber** [comment]
Run `./checkpointctl`

**Comment by anshitha1706** [comment]
Done, it shows all the commands and usage of the tool. but running the command still shows output 'command not found'. Is there something I am doing wrong?

**Comment by adrianreber** [comment]
> Done, it shows all the commands and usage of the tool. but running the command still shows output 'command not found'. Is there something I am doing wrong? :(

What you mean by 'running the command'? First you say ' it shows all the commands and usage' and then 'command not found'.

Not sure what your problem is. Does it work or not?

**Comment by anshitha1706** [comment]
I mean when I run './checkpointctl' on the CLI, it shows me all the commands and usage. Then when I run 'checkpointctl show' on the CLI, its says 'checkpointctl: command not found'. Is it the right way of using it or am I missing something?

**Comment by adrianreber** [comment]
If a binary cannot be found in $PATH you will get 'command not found'. By using `./checkpointctl` you are telling your shell exactly where to find the binary: in the current directory. This is the same with all commands you are using. Either you add the location of `checkpointctl` to your $PATH, or you copy the binary to a location that is already in your search path or you just always use `./checkpointctl`.

**Comment by anshitha1706** [comment]
Ohh Alright! Thank you so much for your help and patience! :)
