### ISSUE TITLE
Dead link to Podman checkpoint

### ISSUE THREAD

**Issue by DuckDuckWhaleUCSD** [checkpoint-restore/checkpointctl#128]
The second link is dead:

Details on how to create checkpoints with the help of [CRIU](https://criu.org/) can be found at:

- [Forensic container checkpointing in Kubernetes](https://kubernetes.io/blog/2022/12/05/forensic-container-checkpointing-alpha/)
- [Podman checkpoint](https://podman.io/getting-started/checkpoint)

Did it get moved to https://podman.io/docs/checkpoint?

**Comment by adrianreber** [comment]
Not sure, we do not control podman.io. But the link you provided looks good. Can you open a PR to fix the README?
