### ISSUE TITLE
Doubt - Relation with Kubernetes

### ISSUE THREAD

**Issue by sapphire006** [checkpoint-restore/checkpointctl#25]
1) Is this a custom kubectl operator ?
2)why was https://github.com/kubernetes/kubernetes/pull/104907 only limited to forensic checkpointing and not restore ? When can this be expected
3)Are there any Pull requests for native kubernetes checkpoint restore support?

**Comment by adrianreber** [comment]
> 1. Is this a custom kubectl operator?

No.

>  2. why was [Minimal checkpointing support kubernetes/kubernetes#104907](https://github.com/kubernetes/kubernetes/pull/104907) only limited to forensic checkpointing and not restore?

To reduce complexity while introducing checkpoint/restore.

> When can this be expected?

The container checkpointed in Kubernetes can be restored outside of Kubernetes. For example in CRI-O.

Once https://github.com/cri-o/cri-o/pull/6181 is merged it should be possible to restore containers also in Kubernetes.

>  3. Are there any Pull requests for native kubernetes checkpoint restore support?

What do you mean?

**Comment by sapphire006** [comment]
By 3) i had meant is anyone actively working on restore part. Once Cri-o Pull request was the thing i was looking for.
Thank you for answering . Grateful for your work on checkpoint restore.
