### ISSUE TITLE
How can I install?

### ISSUE THREAD

**Issue by mind-mind** [checkpoint-restore/checkpointctl#4]
Hi,

 I tried to use this API. I clone this to my machine and I use the command
"make" because you have makefile right? I try to follow the video kubectl-drain-checkpoint.mp4

For some reason, I cannot use the command "checkpointctl", but I use ./checkpointctl with the command

<img width="462" alt="image" src="https://user-images.githubusercontent.com/68138683/118134382-10e5fa00-b42c-11eb-9cd6-0137a46addc5.png">

I got this error 

Error: Target /var/lib/kubelet/checkpoints access error
: stat /var/lib/kubelet/checkpoints: no such file or directory

I don't know how to deal with this? Any recommendation?

**Comment by adrianreber** [comment]
Are you using Kubernetes from my pull request with checkpoint restore support?

Kubernetes does not have support for checkpointing. It is still being discussed upstream.

**Comment by mind-mind** [comment]
I use K8s and CRI-O, Podman.

**Comment by adrianreber** [comment]
You need to use Kubernetes from https://github.com/kubernetes/kubernetes/pull/97194

Without the changes from that pr it is not possible to checkpoint container.

**Comment by mind-mind** [comment]
Thank you though
