### ISSUE TITLE
Add support for showing information for multiple checkpoints

### ISSUE THREAD

**Issue by rst0git** [checkpoint-restore/checkpointctl#53]
The `checkpointctl show` command currently supports displaying the information for a single checkpoint file. However, it would be very useful for this command to be extended with support for multiple files (similar to other Unix commands).

Example:

```bash
checkpointctl show /var/lib/kubelet/checkpoints/*.tar
```

**Comment by behouba** [comment]
Hi @rst0git, 
I would like to work on this.

**Comment by rst0git** [comment]
It sounds like a good idea.

@adrianreber What do you think?

**Comment by adrianreber** [comment]
> It sounds like a good idea.
> 
> @adrianreber What do you think?

Sounds good.

The more important thing from my point of view would be to focus on unpacking only the needed files. Multiple checkpoints can be something for later.

For multiple checkpoints I would at first say to not support the additional flags. Maybe just list all the checkpoints in a single table.

**Comment by behouba** [comment]
Thank you, @adrianreber, for your suggestion. I will also start thinking about #51.

**Comment by adrianreber** [comment]
> Thank you, @adrianreber, for your feedback. I will also start thinking about #51.

Ah, sorry. I got confused. I thought this was #51. Then my comment does not make so much sense.

I still think I would start with a simple show all checkpoints in one table. My use case would be to get a quick overview of all checkpoints.

Details are not so important in that case at first.

**Comment by behouba** [comment]
Alright, I agree that it would be better to initially not support additional flags when handling multiple files. 
What do you think, @rst0git?

**Comment by rst0git** [comment]
> I still think I would start with a simple show all checkpoints in one table. My use case would be to get a quick overview of all checkpoints.

I also agree, using one table with an overview of all checkpoints would be more appropriate.

Example:
```
+----------------+--------------------------------+--------------+---------+---------------------------+--------+------------+-------------------+
|   CONTAINER    |             IMAGE              |      ID      | RUNTIME |          CREATED          | ENGINE | CHKPT SIZE | ROOT FS DIFF SIZE |
+----------------+--------------------------------+--------------+---------+---------------------------+--------+------------+-------------------+
| gallant_austin | docker.io/library/nginx:latest | 5e61a1e0a308 | crun    | 2023-03-01T15:11:55+03:00 | Podman | 16.6 MiB   | 4.5 KiB           |
+----------------+--------------------------------+--------------+---------+---------------------------+--------+------------+-------------------+
| gallant_austin | docker.io/library/nginx:latest | 5e61a1e0a308 | crun    | 2023-03-01T15:11:55+03:00 | Podman | 16.6 MiB   | 4.5 KiB           |
+----------------+--------------------------------+--------------+---------+---------------------------+--------+------------+-------------------+
| gallant_austin | docker.io/library/nginx:latest | 5e61a1e0a308 | crun    | 2023-03-01T15:11:55+03:00 | Podman | 16.6 MiB   | 4.5 KiB           |
+----------------+--------------------------------+--------------+---------+---------------------------+--------+------------+-------------------+

```
