### ISSUE TITLE
Add support for list command

### ISSUE THREAD

**Issue by rst0git** [checkpoint-restore/checkpointctl#54]
There are several standard locations where container engines like Podman and CRI-O store container checkpoints. However, these locations are not well documented and it might be difficult for users to find them. It would be very useful to have a command like `checkpointctl list` that would be able to list container checkpoints created by Podman and CRI-O.

**Comment by Nitishupkr** [comment]
i take up this issue

**Comment by rst0git** [comment]
Hi @Nitishupkr, you are more than welcome to work on this GitHub issue. Please let us know if you have any questions.

**Comment by Parthiba-Hazra** [comment]
@Nitishupkr you still working on this? if not then I can take on.

**Comment by Parthiba-Hazra** [comment]
@rst0git if I am not wrong then container engine store container checkpoints here - 
podman - /var/lib/containers/storage/overlay-containers
CRI-O - /var/run/crio/checkpoints

for the list command are we gonna print the full path of checkpoint containers?
and is there any other directories we also need to check? and what about the checkpoints that are store in the directory specified by the users during the container checkpoint command execution?

**Comment by rst0git** [comment]
@Parthiba-Hazra As a starting point, we can add `checkpointctl list` command that shows checkpoints stored in `/var/lib/kubelet/checkpoints/`. This path is used by [Kubernetes/CRI-O](https://kubernetes.io/blog/2022/12/05/forensic-container-checkpointing-alpha/) and contains files with the following naming convention:

```
checkpoint-<pod-name>_<namespace-name>-<container-name>-<timestamp>.tar
```

Example:
```
checkpoint-counter-tl58j_default-counter-2023-10-12T11:02:56+01:00.tar
```

> for the list command are we gonna print the full path of checkpoint containers?

It would good to use file name parsing and output a table similar to the `checkpointctl show` command. This functionality is particularly useful in scenarios where automated periodic checkpointing is used as a fault-tolerance mechanism, leading to many container checkpoints created in this directory. 

> what about the checkpoints that are store in the directory specified by the users during the container checkpoint command execution?

Once the list command has been merged, we could extend checkpointctl with support for configuration files that enable users to change the default path or to specify additional locations.

@adrianreber Do you have any thoughts?

**Comment by Parthiba-Hazra** [comment]
> @Parthiba-Hazra As a starting point, we can add `checkpointctl list` command that shows checkpoints stored in `/var/lib/kubelet/checkpoints/`. This path is used by [Kubernetes/CRI-O](https://kubernetes.io/blog/2022/12/05/forensic-container-checkpointing-alpha/) and contains files with the following naming convention:
> 
> ```
> checkpoint-<pod-name>_<namespace-name>-<container-name>-<timestamp>.tar
> ```
> 
> Example:
> 
> ```
> checkpoint-counter-tl58j_default-counter-2023-10-12T11:02:56+01:00.tar
> ```
> 
> > for the list command are we gonna print the full path of checkpoint containers?
> 
> It would good to use file name parsing and output a table similar to the `checkpointctl show` command. This functionality is particularly useful in scenarios where automated periodic checkpointing is used as a fault-tolerance mechanism, leading to many container checkpoints created in this directory.
> 
> > what about the checkpoints that are store in the directory specified by the users during the container checkpoint command execution?
> 
> Once the list command has been merged, we could extend checkpointctl with support for configuration files that enable users to change the default path or to specify additional locations.
> 
> @adrianreber Do you have any thoughts?

yes that sounds good.

**Comment by Parthiba-Hazra** [comment]
@rst0git I think this can be closed now.
