### ISSUE TITLE
Do not use the podman network status

### ISSUE THREAD

**Issue by Luap99** [checkpoint-restore/checkpointctl#6]
Podman is going to abstract CNI from libpod (see https://github.com/containers/podman/pull/11232).
When the work is done libpod will no longer use the CNI result as network status. I am currently wiring the new interface into libpod and noticed that the CNI result is dumped into the checkpoint dir and that this library is using the result on restore to the set the ip and mac address. In my opinion this library should not have to know anything about the network status used in podman. I think it would make more sense to handle setting the correct ip and mac entirely in libpod and not here.

**Comment by adrianreber** [comment]
Is that related to #5 ?

**Comment by Luap99** [comment]
> Is that related to #5 ?

Somewhat, I don't how many consumers this lib has but if [GetIPFromNetworkStatus](https://github.com/checkpoint-restore/checkpointctl/blob/main/lib/metadata.go#L198) and [GetMACFromNetworkStatus](https://github.com/checkpoint-restore/checkpointctl/blob/1ca930a3ec850562b6cfd42127f5e373ba0c2141/lib/metadata.go#L211) are only used by Podman I think it is safe to remove CNI completely. If the functions are also used elsewhere then this has to stay obviously.

Anyway the Podman network status will be changed in https://github.com/containers/podman/pull/11322. When the PR is merged this lib will no longer be able to unmarshal this into a CNI result.
