### ISSUE TITLE
Extend the output format with a tree view

### ISSUE THREAD

**Issue by behouba** [checkpoint-restore/checkpointctl#75]
Currently, the output format of `checkpointctl` is in a table format. However, due to the limitations of horizontal space and the need to display multiple checkpoints, it would be beneficial to add a tree view format. This offers several advantages:
- The tree format takes advantage of unlimited vertical space, which is more suitable for displaying detailed information.
- The tree format can be used with multiple checkpoints, allowing for the presentation additional details for each checkpoint.
- A built-in terminal pager, (e.g: `systemctl status`), would enhance the usability of the output.

Here's an example of how the output could look:
```bash
containername
├── IMAGE: registry/name:latest
├── ID: 209872364234
├── RUNTIME: runc
├── CREATED: 2023-05-19T08:44:58.018444733Z
├── ENGINE: CRI-O
├── IP: 10.88.0.11
├── CHECKPOINT SIZE:
├── ROOT FS DIFF SIZE:
├── NAMESPACES:
│   ├── UTSNS
│   │   ├── NODENAME: hostname01
│   │   └── DOMAINNAME: (none)
│   └── IPC
└── PROCESSES
    └── [1]  bash
        ├── [7]  counter.py
        └── [8]  tee

```

Suggested by @adrianreber

**Comment by rst0git** [comment]
It might be useful to to also be able to render the out in JSON format (e.g., similar to `podman inspect`). This would eable easier integration with other tools to further process the output of checkpointctl.
