### ISSUE TITLE
Extend `inspect` output format with JSON

### ISSUE THREAD

**Issue by behouba** [checkpoint-restore/checkpointctl#77]
Currently `checkpointctl inspect` only support the tree format. It might be useful to also be able to render the output in a JSON format (`--format=json`). This would enable easier integration with other tools to further process the output of checkpointctl.

Suggested by: @rst0git

**Comment by snprajwal** [comment]
This would be trivial to do for the existing features coming from CRIT (process tree, file descriptors, etc) since the original format is JSON itself. At most, we will have to use a custom struct to remove some of the fields that are not relevant.

**Comment by Parthiba-Hazra** [comment]
Hi @behouba @snprajwal @rst0git 
if the issue is not been worked yet, can I take it ?

**Comment by rst0git** [comment]
@Parthiba-Hazra Sure, please feel free to open a pull request!
